### ISSUE TITLE
Add contributing doc

### ISSUE THREAD

**Issue by chrisjsimpson** [KarmaComputing/salon-booking-guru#6]
**Is your feature request related to a problem? Please describe.**

Add contributing doc to make clear issue creation and branching strategy and their relation

**Describe the solution you'd like**
Document how issues and branch names are created on this project

**Describe alternatives you've considered**

**Additional context**

**Comment by deltabrot** [comment]
Resolved in 1d1d3df6ec2b8891ca877210ddb9fb87a3fb0c0b
